"""empty message

Revision ID: 20e6d7954c10
Revises: 
Create Date: 2024-03-18 09:29:46.008068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e6d7954c10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_users', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_users', sa.String(length=155), nullable=False),
    sa.Column('NIK', sa.Integer(), nullable=False),
    sa.Column('alamat', sa.String(length=355), nullable=False),
    sa.Column('jenis_pajak', sa.String(length=355), nullable=False),
    sa.Column('nama_obyek_pajak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_users')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
