"""empty message

Revision ID: 28f4885c3c79
Revises: b92f9418e2ac
Create Date: 2024-03-20 07:56:13.315792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28f4885c3c79'
down_revision = 'b92f9418e2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelaporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tahun_pelaporan', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tahun_pembayaran', sa.Integer(), nullable=True))
        batch_op.drop_column('tahun')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelaporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tahun', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('tahun_pembayaran')
        batch_op.drop_column('tahun_pelaporan')

    # ### end Alembic commands ###
