"""empty message

Revision ID: b92f9418e2ac
Revises: d2b36215d461
Create Date: 2024-03-20 07:16:51.516778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92f9418e2ac'
down_revision = 'd2b36215d461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelaporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_pembayaran', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelaporan', schema=None) as batch_op:
        batch_op.drop_column('status_pembayaran')

    # ### end Alembic commands ###
