"""empty message

Revision ID: d137f063ed45
Revises: ef6dc199c0f2
Create Date: 2024-03-18 10:03:25.790464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd137f063ed45'
down_revision = 'ef6dc199c0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NPWP', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('NPWP')

    # ### end Alembic commands ###
