"""empty message

Revision ID: ef6dc199c0f2
Revises: 20e6d7954c10
Create Date: 2024-03-18 09:40:04.324841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef6dc199c0f2'
down_revision = '20e6d7954c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('jenis_pajak',
               existing_type=mysql.VARCHAR(length=355),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('nama_obyek_pajak',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=155),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nama_obyek_pajak',
               existing_type=sa.String(length=155),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('jenis_pajak',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=355),
               existing_nullable=False)

    # ### end Alembic commands ###
